### ISSUE TITLE
Neos Setup breaks if no Database connection is configured

### ISSUE THREAD

**Issue by bwaidelich** [neos/neos-development-collection#1663]
### Description

When trying to access the Setup tool Neos provides, an exception is thrown that prevents the user from accessing the Setup.

### Steps to Reproduce

1. Install a fresh Neos (2.3-dev, 3.0-dev, 3.1-dev or dev-master)
2. Try to access the Frontend
3. Follow the instructions to enter the Setup tool

#### Expected behavior

At first an Database Error is thrown, as expected:

![image](https://user-images.githubusercontent.com/307571/28971486-650b7040-792c-11e7-998b-3a18ad47928c.png)

When clicking on *Go to setup*, the Setup Tool should be displayed.

#### Actual behavior

Dev Context:

![image](https://user-images.githubusercontent.com/307571/28971507-7a030fe4-792c-11e7-8a01-74e7caeb5388.png)

Production Context:

![image](https://user-images.githubusercontent.com/307571/28971515-81eb886c-792c-11e7-8310-457ebf4783c1.png)

### Affected Versions

Neos: 2.3.x-dev, 3.0-dev, 3.1-dev, dev-master

**Comment by kitsunet** [comment]
Why is this marked with next major tag? Shouldn't this be fine with #926 now?

**Comment by bwaidelich** [comment]
@kitsunet How is this related?

**Comment by bwaidelich** [comment]
Ah, sorry, neos/flow-development-collection#926 you mean

**Comment by bwaidelich** [comment]
I added the label before I pushed a fix. But yes, that should do

**Comment by H45AN** [comment]
I have just done a fresh install with composer today and this is still broken.

```
    [array] =>
        previousException:
        [string] => Exception #1045 in line 44 of /var/www/domains/neos/Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)
```

<img width="809" alt="screen shot 2018-02-22 at 14 33 10" src="https://user-images.githubusercontent.com/2689860/36541179-5b076996-17dd-11e8-9d45-145fffe41bba.png">

**Comment by H45AN** [comment]
@bwaidelich can you please re-open the issue. Thanks

**Comment by bwaidelich** [comment]
@H45AN is the *setup* really broken for you? (what happens if you click that "Go to setup" button above?

**Comment by H45AN** [comment]
@bwaidelich Yep it is broken, it keeps switching between initial password from Data file to this error. as you can see in the gif below.

![kapture 2018-02-22 at 15 10 35](https://user-images.githubusercontent.com/2689860/36543009-cae74718-17e2-11e8-825b-07a2682412f8.gif)

**Comment by bwaidelich** [comment]
@H45AN Thanks for clearifying. That's not good. I re-opened the ticket

**Comment by H45AN** [comment]
@bwaidelich Thanks! do know you how i can bypass this setup wizard and install for the neos for the moment.

**Comment by bwaidelich** [comment]
@H45AN I just tried to reproduce the issue with latest Neos but it works for me without DB connection. 
Which version did you install, i.e. what commands did you execute?

> do know you how i can bypass this setup wizard

You can just setup the DB credentials manually like described in the [Flow manual](http://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartII/Configuration.html#database-setup)

**Comment by bwaidelich** [comment]
@H45AN did you also check the comments on #1691?

**Comment by H45AN** [comment]
@bwaidelich I used the following commands.

```
composer create-project neos/neos-base-distribution ./
sudo ./flow core:setfilepermissions mtm-ninja www-data www-data
```
Running php7.2, mysql5.17...

**Comment by aertmann** [comment]
I've previously seen different behavior between wrong credentials and the database not existing at all, which one is it in your case @H45AN?

**Comment by H45AN** [comment]
@aertmann The database service is running, as it is hosting other test sites. As you can see in the above .gif the issue happens on neos first boot after download with composer. I never get to put the database credentials for the project.

**Comment by bwaidelich** [comment]
Thanks for the info, that makes debugging a bit easier I guess.. Still, I couldn't reproduce it so far with latest Neos and mariadb. and it seems neos/flow-development-collection#926 only fixed this for 3.3+

**Comment by H45AN** [comment]
@bwaidelich Are you using Neos , mariadb and Nginx ? because it seems other people had the same issue with nginx https://discuss.neos.io/t/solved-neos-installation-nginx/1882/7

**Comment by bwaidelich** [comment]
No, currently using mariadb as service (on Mac OS) and the PHP based server from Flow

**Comment by H45AN** [comment]
Exactly, my dev box with php server from flow also works on mac os but the issue happens on our testing server where the stack is
- Nginx/1.10.3 (Ubuntu)
- PHP 7.2.2-3+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  6 2018 16:11:23) ( NTS )
- MySQL 5.7.21-0ubuntu0.16.04.1  (Root password protected.)
- Composer version 1.6.3 2018-01-31 16:28:17

**Comment by aertmann** [comment]
Just tried myself as well, cannot reproduce.

Nginx 1.12.2, PHP 7.2, MySQL 5.7.21, Composer 1.6.2

**Comment by bwaidelich** [comment]
Sorry, I had to unassign myself from this ticket again because I still can't reproduce the issue atm.. If someone could debug where exactly that error occurs (and possibly, why) - that would be much appreciated..

**Comment by bwaidelich** [comment]
Thanks, I will close the ticket.
Feel free to re-open/comment if the problem persists

**Comment by masterpi227** [comment]
issue is remaining
after starting neos with flow server:run , tried to enter setup
Apache 2.4.27, PHP 7.2.19, MariaDB 10.1.40, Composer 1.6.3

An exception occurred in driver: SQLSTATE[HY000] [1698] Access denied for user ''@'localhost'
Exception Code	0
Exception Type	Doctrine\DBAL\Exception\DriverException
Thrown in File	Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php
Line	106

Nested Exception
SQLSTATE[HY000] [1698] Access denied for user ''@'localhost'
Exception Code	1698
Exception Type	Doctrine\DBAL\Driver\PDOException
Thrown in File	Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php
Line	31

Nested Exception
SQLSTATE[HY000] [1698] Access denied for user ''@'localhost'
Exception Code	1698
Exception Type	PDOException
Thrown in File	Packages/Libraries/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php
Line	27

**Comment by mkeitsch** [comment]
I run into this error today. I tried a bit and found out, that this loop occurs on my system, if the rewrite rules are missing to remove the .../index.php/... part from the link path.
So, I can't run into the setup correctly, if I run Flow/Neos via the built-in web server of PhpStorm. But with the command line server of Neos/Flow it worked just fine and the "index.php" part was not included.

**Comment by AureliusHogan** [comment]
Had the same problem today as well. I could solve the problem after I disabled my special settings in .htaccess for FLOW_CONTEXT. I would have loaded **FLOW_CONTEXT=Production/OnTest**. Setting **FLOW_CONTEXT** to **Development** solved the problem.

It works fine with my development environment. Is sub FLOW_CONTEXT conditional to something?

**Comment by Robin-Whittle** [comment]
Thanks AureliusHogan for your message.  I know nothing of CMSes and had followed various instructions to install on Debian 10, nginx, LetsEncrypt (Certbot did the work, and I instructed it to have the server reload http connections to https), MariaDB and now Neos.  After an apparently successful installation, the public site (frontend) rendered without proper formatting (now I have seen how it should look) - it looked like a plain HTML page without any menu at the top etc, with a big picture of the beach and a narrow horizontal bar which I now realise was part of the cake image.  The editing site (backend) which I had successfully logged into via https://example.com/neos/login showed only a full window pulsating 'N'.  

The fix was to change "fastcgi_param   FLOW_CONTEXT      Production;" to "fastcgi_param   FLOW_CONTEXT      Development;" in the nginx server block file and restart (reload would have worked too?) nginx.  Then everything now looks OK - but I am just a newbie.  The frontend shows a CMS-like page with a cake and menu items.  The backend shows the same thing with lots of editing options.

In case anyone is interested, here is the full nginx server block file.  The Certbot stuff is for LetsEncrypt.  Most of the rest of it I copied from various websites and do not understand.

    server {
            root /home/robin/site-16-5nn/htdocs/neoscms/Web;
            index index.php index.html index.htm;
    
            server_name 5nn.info;
    
            client_max_body_size 100M;
    
            access_log /home/robin/site-16-5nn/logs/access_log.txt;
            error_log  /home/robin/site-16-5nn/logs/error_log.txt;
    
            location / {
                    try_files $uri $uri/ /index.php?$args;
            }
    
            location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param   FLOW_CONTEXT      Development;
            fastcgi_param   FLOW_REWRITEURLS  1;
            include fastcgi_params;
            }
    
        listen [::]:443 ssl ipv6only=on; # managed by Certbot
        listen 443 ssl; # managed by Certbot
        ssl_certificate /etc/letsencrypt/live/5nn.info/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/5nn.info/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    }
    
    server {
        if ($host = 5nn.info) {
            return 301 https://$host$request_uri;
        } # managed by Certbot
    
            listen 80;
            listen [::]:80;
    
            server_name 5nn.info;
        return 404; # managed by Certbot
    }

I am using nginx 1.14.2, PHP 7.3, MariaDB 10.3.22-MariaDB-0+deb10u1 Debian 10 and Neos (where can I find a version?) downloaded from github 2020-05-13 according to the instructions https://websiteforstudents.com/setup-neos-cms-framework-on-ubuntu-16-04-18-04-18-10-with-nginx-mariadb-and-php-7-2-fpm/ which were the basis for how I installed MariaDB and Neos.

**Comment by AureliusHogan** [comment]
I'm so sorry!!!
After some more trying I found a damn typo. The username that I used was wrong in the configuration for the FLOW_CONTEXT=Production/OnTest. The font I used didn't make a difference between I (big i) and l (small L, as it doesn't here as well).

So everything is fine. But I forgot of this ticket. Sorry!!

**Comment by Robin-Whittle** [comment]
Hi Aurelius, this is a good argument for programs using the famously ugly Courier New font or similar for anything technical, including all source code editing, passwords, usernames etc. - ideally with a slash zero.  

I am not sure if my note above is useful to anyone.  I found that not even the extraordinarily sophisticated (and to me bafflingly complex) Neos gave me the control I wanted over text, so I am back to using Kompozer.
